app:
  firebase-configuration-file: moslavac-9d4c8-firebase-adminsdk-jgmzm-f2fb4aecb9.json

spring:
  codec:
    max-in-memory-size: 10MB
  application:
    name: Moslavac
  datasource:
    url: jdbc:postgresql://localhost:5432/moslavac
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  api:
    hns:
      key: bd993d1e4919fd190ef3822902f81fa7a2a9f30f90a7b998f560b8ac21d4acabb62206f59cd09cac7089dbb7df709793c1b4b3a8ddf1596729eb6d5ae61d7f97
      base-url: https://api-hns.analyticom.de
      team-id: 1337
  admin:
    password: Moslavac33
