spring:
  application:
    name: Moslavac
  datasource:
    url: jdbc:postgresql://localhost:5432/moslavac
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  mail:
    host: smtp.gmail.com
    port: 587
    password: gnoj imwz xxvj xhmm
    username: adrianofaletar@gmail.com
    properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true

